# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishTestResults@2
  displayName: 'Publish Unit Test Results'
  condition: succeededOrFailed()
  inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      publishRunAttachments: true
      testRunTitle: 'React App Test'
- task: ado-testingextension@1
  inputs:
      Operation: 'createTests'
      DevOpsUrl: 'https://dev.azure.com/BenedicentiKoragod'
      AzureProjectName: 'Java Pipeline'
      PAT: 'ffh73pcazmjdtb4vs5vm6zjwsfgb2obwrmpry7j7x7pjuykonzwq'
      DotnetExePath: 'C:\Program Files\dotnet\dotnet.exe'
      RepoName: 'https://BenedicentiKoragod@dev.azure.com/BenedicentiKoragod/Java%20Pipeline/_git/Java%20Pipeline'
      FeatureFilePath: '**/surefire-reports/TEST-*.xml'
      AreTheseDotnetTests: 'false'
      